version: '2'
services:
  security:
    build: ./sample-service
    ports:
     - "8123:8123"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./sample-service/api:/app/api
  db:
    build: ./database-service
